name: On Merge Run AML Training Job

on: 
  pull_request:
    types:
      - closed


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set Azure ML workspace as default
      run: |
        az configure --defaults group="kapildhanger-rg"
        az configure --defaults workspace="kdmlworkspace"
    - name: Run AML Training Job
      run: |
        cd src
        az ml job create --file job.yml